default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: email_api_development

test:
  <<: *default
  database: email_api_test

production:
  <<: *default
  database: email
  username: <%= ENV['EMAIL_DATABASE_USERNAME'] %>
  password: <%= ENV['EMAIL_DATABASE_PASSWORD'] %>
