default: &default
  adapter: postgresql
  encoding: unicode
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  database: 'email_api_development'
  username: 'julian'
  password: '123456'
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
